export const loadingMessages = [
    "Generating witty dialog...",
    "Swapping time and space...",
    "Bending the spoon...",
    "The architects are still drafting...",
    "The bits are breeding...",
    "...and enjoy the elevator music...",
    "Don't worry - a few bits tried to escape, but we caught them...",
    "...at least you're not on hold...",
    "The bits are flowing slowly today...",
    "(Insert quarter)",
    "It's not you. It's me...",
    "Spinning the wheel of fortune...",
    "Computing chance of success...",
    "Please wait until the sloth starts moving...",
    "Listening for the sound of one hand clapping...",
    "Putting the icing on the cake...",
    "Cleaning off the cobwebs...",
    "Making sure all the i's have dots...",
    "Granting wishes...",
    "Convincing AI not to turn evil...",
    "Computing the secret to life, the universe, and everything...",
    "Locating the One Piece...",
    "Waiting for the paint to dry...",
    "Dividing by zero...",
    "Entangling superstrings...",
    "Trying to sort in O(n)...",
    "Looking for sense of humour, please hold on...",
    "Kindly hold on as we convert this bug to a feature...",
    "Ordering 1s and 0s...",
    "Mining some bitcoins...",
    "Updating to Windows Vista...",
    "Pushing pixels...",
    "Debugging Debugger...",
    "Work, work...",
    "Feeding the unicorns...",
    "Up, Up, Down, Down, Left, Right, Left, Right, B, A.",
    "One mississippi, two mississippi...",
    "Baking ice cream...",
    "Doing some heavy lifting...",
    "Sprinkling some sugar...",
    "Trying to rhyme a word with orange...",
    "Finding a four leaf clover..."
];

// Loading Messages From https://gist.github.com/meain/6440b706a97d2dd71574769517e7ed32